# -*- coding: utf-8 -*-
"""BasicRAG_01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sP4JA5B198dCFb2jSsD2hi_lqql2C5dq

📄 FREE PDF-BASED RAG (Google Colab)
What we are building (simple words)

“Upload a PDF → break it into chunks → store meaning → ask questions → get answers”

STEP 1: Install PDF + RAG libraries
"""

!pip install -q \
pypdf \
sentence-transformers \
transformers \
accelerate \
chromadb \
langchain \
langchain-community \
langchain-text-splitters

"""STEP 2: Import Required Modules

"""

from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_community.vectorstores import Chroma
from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_community.llms import HuggingFacePipeline
from langchain_community.document_loaders import PyPDFLoader

from transformers import pipeline

"""STEP 3: Upload PDF in Google Colab"""

from google.colab import files

uploaded = files.upload()

"""STEP 4: Load PDF Content

"""

loader = PyPDFLoader("Cracking the Coding Interview.pdf")
documents = loader.load()

print("Total pages loaded:", len(documents))

"""STEP 5: Chunk the PDF

"""

text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=500,
    chunk_overlap=100
)

chunks = text_splitter.split_documents(documents)

print("Total chunks created:", len(chunks))

for i in range(min(20, len(chunks))):
    print(f"\nChunk {i+1}:\n", chunks[i].page_content[:500])

"""STEP 6: Create FREE Embeddings (No API)

"""

embedding_model = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-MiniLM-L6-v2"
)

"""STEP 7: Store Chunks in Vector Database"""

vector_db = Chroma.from_documents(
    documents=chunks,
    embedding=embedding_model
)

"""STEP 8: Ask a Question from the PDF"""

query = input("What quetion you want to know")

"""STEP 9: Retrieve Relevant PDF Chunks"""

retrieved_docs = vector_db.similarity_search(query, k=3)

print("Retrieved context:\n")
for doc in retrieved_docs:
    print("-", doc.page_content[:300])

"""STEP 10: Load FREE LLM

"""

hf_pipeline = pipeline(
    "text2text-generation",
    model="google/flan-t5-small",
    max_new_tokens=200
)

llm = HuggingFacePipeline(pipeline=hf_pipeline)

"""STEP 11: Build Grounded Prompt"""

context = "\n".join([doc.page_content for doc in retrieved_docs])

prompt = f"""
Answer the question using ONLY the context below.
If the answer is not present, say "I don't know" and then give answer absed on your search.

Context:
{context}

Question:
{query}
"""

"""STEP 12: Generate Answer from PDF"""

answer = llm.invoke(prompt)
print("Question is" , query)
print("Answer:\n", answer)

